import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Unused variables/parameters: tsc covers them with noUnusedLocals / noUnusedParameters, this
  // rule covers the ESLint side (both must use the same ignore convention). Prefix parameters you
  // need to keep but don't use with `_`.
  {
    files: ["**/*.{ts,tsx,mts}"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  // Kit code always uses the logger (src/core/observability), never console.error / warn directly.
  // console.info is reserved for local hints in development such as printing email contents;
  // skip notices in tests are not restricted.
  {
    files: ["src/core/**/*.{ts,tsx}"],
    ignores: [
      "src/core/**/*.test.{ts,tsx}",
      "src/core/observability/logger.ts",
    ],
    rules: { "no-console": ["error", { allow: ["info"] }] },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "playwright-report/**",
    "test-results/**",
    // Post data generated by content-collections
    ".content-collections/**",
  ]),
]);

export default eslintConfig;
