import type { Metadata } from "next";

import { openGraphLocales } from "@/core/i18n/locales";

import siteConfig from "../../../site.config";
import { ogImageSize } from "./og-image-size";
import { absoluteUrl, languageAlternates, siteUrl } from "./urls";

export type BuildMetadataOptions = {
  locale: string;
  /**
   * Site-relative path without the locale prefix, e.g. "/" or "/privacy".
   *
   * `null` means the page has no canonical address of its own (404): no canonical or hreflang is
   * emitted, and Open Graph gets no url — see the alternates / openGraph comments below. It is an
   * explicit `null` rather than an optional parameter so "this page has no canonical" has to be
   * written out.
   */
  path: string | null;
  /** Page title, applied to the `%s | Site name` template. Defaults to the site name (for the home page and root layout). */
  title?: string;
  /** Defaults to the site description. */
  description?: string;
  /** Site-relative path or absolute URL of the share image (optionally with dimensions); defaults to the brand image generated by `src/app/opengraph-image.tsx`. */
  image?: string | { url: string; width: number; height: number; alt?: string };
  /** Set to true for pages that search engines shouldn't index. */
  noIndex?: boolean;
  /** When a page exists in only some locales, list them and hreflang emits only those. Defaults to all locales. */
  locales?: readonly string[];
  /** Passed by post pages: switches the Open Graph type to article and adds the publish time and tags. */
  article?: { publishedTime: string; tags: string[] };
  /** Extra `<link rel="alternate">` entries grouped by MIME type, e.g. RSS. */
  feeds?: Record<string, { url: string; title: string }[]>;
};

const defaultImage = {
  url: "/opengraph-image",
  width: ogImageSize.width,
  height: ogImageSize.height,
  alt: siteConfig.name,
};

/**
 * Builds page metadata in one place: title template, description, canonical, hreflang, Open Graph,
 * Twitter. The root layout lives under [locale], so the app-root opengraph-image isn't injected
 * automatically and is referenced explicitly.
 */
export function buildMetadata({
  locale,
  path,
  title,
  description = siteConfig.description,
  image,
  noIndex = false,
  locales,
  article,
  feeds,
}: BuildMetadataOptions): Metadata {
  const fullTitle = title ? `${title} | ${siteConfig.name}` : siteConfig.name;
  const images = [
    typeof image === "string" ? { url: image } : (image ?? defaultImage),
  ];

  // A page with path null (404) has no canonical address: no canonical / hreflang may be emitted,
  // but simply leaving the field out isn't enough — Next shallow-merges metadata per field, so a
  // field the child omits is inherited from the layout, and the 404 would carry a canonical
  // pointing at the home page. The empty object is an explicit override: Next's resolveAlternates
  // returns `{ canonical: null, languages: null, ... }` for `{}`, so this page's head has no
  // canonical / hreflang at all (other pages still pass their real path, unchanged). The same
  // applies to openGraph.url below.
  const alternates: Metadata["alternates"] =
    path === null
      ? {}
      : {
          canonical: absoluteUrl(locale, path),
          languages: languageAlternates(path, locales),
          ...(feeds && { types: feeds }),
        };

  return {
    metadataBase: new URL(siteUrl),
    title: title
      ? { absolute: fullTitle }
      : { default: siteConfig.name, template: `%s | ${siteConfig.name}` },
    description,
    alternates,
    openGraph: {
      ...(article
        ? { type: "article", ...article }
        : { type: "website" as const }),
      siteName: siteConfig.name,
      locale: openGraphLocales[locale] ?? locale,
      ...(path !== null && { url: absoluteUrl(locale, path) }),
      title: fullTitle,
      description,
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images,
    },
    ...(noIndex && { robots: { index: false, follow: false } }),
  };
}
